SELECT EXTRACT(YEAR FROM S.SALES_DATE) AS YEAR,
       EXTRACT(MONTH FROM S.SALES_DATE) AS MONTH,
       I.GENDER,
       COUNT(DISTINCT I.USER_ID) AS USERS
FROM USER_INFO I
INNER JOIN ONLINE_SALE S
    ON I.USER_ID = S.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM S.SALES_DATE), EXTRACT(MONTH FROM S.SALES_DATE), I.GENDER
ORDER BY YEAR, MONTH, I.GENDER;
