SELECT A.PRODUCT_ID, B.PRODUCT_NAME , SUM(A.AMOUNT * B.PRICE) AS TOTAL_SALES FROM (
(SELECT PRODUCT_ID , PRODUCE_DATE ,SUM(AMOUNT) AS AMOUNT 
FROM FOOD_ORDER
GROUP BY PRODUCT_ID , 
PRODUCE_DATE HAVING TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05' ORDER BY PRODUCT_ID) A INNER JOIN FOOD_PRODUCT B
ON A.PRODUCT_ID = B.PRODUCT_ID)
GROUP BY A.PRODUCT_ID , B.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC , A.PRODUCT_ID ASC
