SELECT B.HOUR, NVL(A.COUNT, 0) AS COUNT
FROM
(SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY TO_CHAR(DATETIME, 'HH24')
    ORDER BY HOUR) A,
(SELECT (LEVEL-1) AS HOUR
    FROM DUAL CONNECT BY LEVEL <= 24) B
WHERE B.HOUR = A.HOUR(+)
ORDER BY HOUR;