SELECT 
    A.MEMBER_NAME,
    B.REVIEW_TEXT,
    TO_CHAR(B.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM 
    MEMBER_PROFILE A
    INNER JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
WHERE 
    B.MEMBER_ID = (
        SELECT MEMBER_ID
        FROM (
            SELECT MEMBER_ID, COUNT(MEMBER_ID) AS MEMBER_COUNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY MEMBER_COUNT DESC
        )
        WHERE ROWNUM = 1
    )
ORDER BY 
    TO_DATE(REVIEW_DATE, 'YYYY-MM-DD') ASC,
    B.REVIEW_TEXT ASC;
