SELECT
A.TITLE AS TITLE
,A.BOARD_ID AS BOARD_ID
,B.REPLY_ID AS REPLY_ID  
,B.WRITER_ID  AS WRITER_ID   
,B.CONTENTS  AS CONTENTS 
,TO_CHAR(B.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD A, USED_GOODS_REPLY B
WHERE A.BOARD_ID = B.BOARD_ID
AND  TO_CHAR(A.CREATED_DATE,'YYYY-MM') = '2022-10'
ORDER BY B.CREATED_DATE ASC , A.TITLE ASC